apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-writer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: writer
        image: sensor-writer:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          value: "redis-0.redis-service"